[build]
  publish = "_site"
  command = "npm run build"

# Simple redirects rule to redirect all unknown links to home page

[[redirects]]
  from = "/*"
  to = "/"
  status = 301

[[redirects]]
from = "/japan/*"
to = "https://11ty-orh-japan.netlify.app/:splat"
status = 200

[[redirects]]
  from = "/japan/*"
  to = "/:splat"